// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gecwfcexufkvdkndbjip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlY3dmY2V4dWZrdmRrbmRiamlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzY4MzksImV4cCI6MjA2MzAxMjgzOX0.dtgj7rmNnMR2z7pXClKAx-s0dIXUx7q95A7wyX9IZbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);